- name: Create template
  template:
    src: resources.yaml.j2
    dest: /tmp/resources.yaml
- name: Apply template
  command: oc apply -f /tmp/resources.yaml
- name: Find existing backend image
  shell: oc get images -n {{ namespace }} | grep "{{ namespace}}/mannequin@"
  register: existing_backend
  ignore_errors: true
- name: Build backend
  when: existiing_backend is failed
  command: oc start-build mannequin-builder
- name: Wait for backend to come up
  uri:
    url: "backend.{{ wildcard_domain }}"
  register: backend_status
  until: backend_status is succeeded
  delay: 3
  retries: 20