# This playbook starts driver, proxy and backend
# Run with --tags shutdown to stop all services
- hosts: backend
  tags: [ 'backend' ]
  tasks:
  - include_role:
      name: "{{ backend_impl }}"
    tags: always
- hosts: proxy
  tags: [ 'proxy' ]
  tasks:
  - name: Create proxy dir
    when: proxy_impl is defined
    file:
      path: '{{ proxy_dir }}'
      state: directory
  - when: proxy_impl is defined
    include_role:
      name: "{{ proxy_impl }}"
    tags: always
- hosts: driver-master
  tags: [ 'driver' ]
  vars:
    hyperfoil_role: controller
  roles:
  - hyperfoil.hyperfoil_setup
- hosts: driver-agent
  tags: [ 'driver' ]
  vars:
    hyperfoil_role: agent
  roles:
  - hyperfoil.hyperfoil_setup
