# This playbook starts driver, proxy and backend
# Run with --tags shutdown to stop all services
- hosts: backend
  tags: [ 'backend' ]
  tasks:
  - include_role:
      name: "{{ backend_impl }}"
    tags: always
- hosts: proxy
  tags: [ 'proxy' ]
  when: proxy_impl is defined
  tasks:
  - name: Create proxy dir
    file:
      path: '{{ proxy_dir }}'
      state: directory
  - include_role:
      name: "{{ proxy_impl }}"
    tags: always
- hosts: driver-master
  tags: [ 'driver' ]
  tasks:
  vars:
    hyperfoil_role: controller
  roles:
  - driver-hyperfoil
- hosts: driver-agent
  tags: [ 'driver' ]
  roles:
  - driver-hyperfoil
