# This playbook starts driver, proxy and backend
# Run with --tags shutdown to stop all services
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: "Build Backend"
    command: 'mvn install'
    args:
      chdir: backend-vertx
- hosts: backend
  roles:
  - backend-vertx
- hosts: proxy
  roles:
  - proxy-envoy
- hosts: driver
  roles: 
  - driver-sailrocket
