- name: Kill old backend
  tags: [ 'shutdown' ]
  command: pkill -f backend-vertx
  failed_when: false
- name: Create backend dir
  file:
    path: '{{ backend_dir }}'
    state: directory
- name: Copy Vert.x backend
  copy:
    src: '{{ inventory_dir }}/backend-vertx/target/backend-vertx-{{ version }}-fat.jar'
    dest: '{{ backend_dir }}/backend-vertx-{{ version }}-fat.jar'
- name: Run Vert.x backend
  shell: >
    java -Dbackend.port={{ backend_port }} -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory
    {% if backend_servers is defined %}
    -Dbackend.servers={{ backend_servers }}
    {% endif %}
    {% if libperfjava is defined %}
    -XX:+PreserveFramePointer -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -agentpath:{{ libperfjava }}
    {% endif %}
    {% if backend_log_config is defined %}
    -Dlog4j.configurationFile=file://{{ backend_log_config }}
    {% endif %}
    -jar {{ backend_dir }}/backend-vertx-{{ version }}-fat.jar
    &> {{ backend_dir }}/vertx.log
  async: 100000
  poll: 0
