- name: Kill old backend
  tags: [ 'shutdown' ]
  command: pkill -f mannequin
  failed_when: false
- name: Create backend dir
  file:
    path: '{{ backend_dir }}'
    state: directory
- name: Clone Mannequin
  git:
    repo: https://github.com/RedHatPerf/mannequin
    dest: '{{ backend_dir }}/mannequin'
- name: Build backend
  command: 'mvn install'
  args:
    chdir: '{{ backend_dir }}/mannequin'
- name: Run Vert.x backend
  shell: >
    java -Dbackend.port={{ backend_port }} -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory
    {% if backend_servers is defined %}
    -Dbackend.servers={{ backend_servers }}
    {% endif %}
    {% if backend_workers is defined %}
    -Dvertx.options.workerPoolSize={{ backend_workers }}
    {% endif %}
    {% if libperfjava is defined %}
    -XX:+PreserveFramePointer -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -agentpath:{{ libperfjava }}
    {% endif %}
    {% if backend_log_config is defined %}
    -Dlog4j.configurationFile=file://{{ backend_log_config }}
    {% endif %}
    {% if backend_jfr == true %}
    -XX:+UnlockCommercialFeatures -XX:+FlightRecorder
    -XX:StartFlightRecording=compress=false,delay=10s,duration=24h,settings=profile,filename={{ backend_dir }}/backend-{{ backend_port }}.jfr
    {% endif %}
    -jar {{ backend_dir }}/mannequin/target/mannequin-{{ backend_version }}-fat.jar
    &> {{ backend_dir }}/vertx-{{ backend_port }}.log
  async: 100000
  poll: 0
