- name: Kill old proxy
  tags: [ 'shutdown' ]
  command: pkill socat
  failed_when: false
- name: Start Socat
  shell: 'socat TCP-LISTEN:{{ proxy_port }},fork,bind={{ proxy_host }} TCP:{{ backend_host }}:{{ backend_port }} &> {{ proxy_dir }}/socat.log'
  async: 100000
  poll: 0