- name: Kill old SailRocket
  tags: [ 'shutdown' ]
  command: 'pkill -f sailrocket-{{ sailrocket_version }}/bin'
  failed_when: false
- name: Create driver dir
  file:
    path: '{{ driver_dir }}'
    state: directory
- name: Copy distribution
  maven_artifact:
    group_id: io.sailrocket
    artifact_id: distribution
    extension: zip
    version: '{{ sailrocket_version }}'
    dest: '{{ driver_dir }}/sailrocket-{{ sailrocket_version }}.zip'
    repository_url: '{{ sailrocket_repository }}'
    verify_checksum: always
- name: Unpack distribution
  unarchive:
    src: '{{ driver_dir }}/sailrocket-{{ sailrocket_version }}.zip'
    dest: '{{ driver_dir }}'
    remote_src: false
- name: Start SailRocket
  #-XX:+UnlockCommercialFeatures -XX:+FlightRecorder
  #-XX:StartFlightRecording=compress=false,delay=10s,duration=24h,settings=profile,filename={{ driver_dir }}/sailrocket.jfr
  shell: >
    {{ driver_dir }}/sailrocket-{{ sailrocket_version }}/bin/standalone.sh
    {% if libperfjava is defined %}
    -XX:+PreserveFramePointer -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -agentpath:{{ libperfjava }}
    {% endif %}
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    -ea
    -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath={{ driver_dir }}
    {% if driver_log_config is defined %}
    -Dlog4j.configurationFile=file://{{ driver_log_config }}
    {% endif %}
    -Dio.sailrocket.rootdir={{ driver_dir }}/workspace
    -Dio.sailrocket.controller.host={{ sailrocket_controller_host }}
    -Dio.sailrocket.controller.port={{ sailrocket_controller_port }}
    &> {{ driver_dir }}/driver.log
  async: 100000
  poll: 0