- name: Kill old proxy
  command: pkill -f {{ envoy_bin }}
  failed_when: false
- name: Create proxy dir
  file:
    path: '{{ proxy_dir }}'
    state: directory
- name: Copy config template
  template:
    src: config.yaml.j2
    dest: '{{ proxy_dir }}/config.yaml'
- name: Start Envoy
  shell: '{{ envoy_bin }} -c {{ proxy_dir }}/config.yaml &> {{ proxy_dir }}/envoy.log'
  async: 100000
  poll: 0
- name: Shutdown Envoy
  tags: ['never', 'shutdown']
  command: 'pkill -f {{ envoy_bin }}'
  failed_when: false