- name: Kill old proxy
  tags: [ 'shutdown' ]
  command: pkill -f {{ envoy_bin }}
  failed_when: false
- name: Copy config template
  template:
    src: '{{ proxy_config }}.yaml.j2'
    dest: '{{ proxy_dir }}/envoy-config.yaml'
- name: Start Envoy
  shell: '{{ envoy_bin }} -c {{ proxy_dir }}/envoy-config.yaml &> {{ proxy_dir }}/envoy.log'
  async: 100000
  poll: 0
