- name: Kill old proxy
  tags: [ 'shutdown' ]
  command: pkill -f {{ envoy_bin }}
  failed_when: false
- name: Copy config template
  template:
    src: '{{ proxy_config }}.yaml.j2'
    dest: '{{ proxy_dir }}/envoy-config-{{ proxy_port }}.yaml'
- name: Start Envoy
  shell: >
    {{ envoy_bin }} -c {{ proxy_dir }}/envoy-config-{{ proxy_port }}.yaml --base-id {{ proxy_port }}
    {% if proxy_workers is defined %}
    --concurrency {{ proxy_workers }}
    {% endif %}
    &> {{ proxy_dir }}/envoy-{{ proxy_port }}.log
  async: 100000
  poll: 0
